### ISSUE TITLE
FR2.2/2.3 User Matching Process

### ISSUE THREAD

**Issue by boonhaii** [CS3219-AY2223S1/cs3219-project-ay2223s1-g39#4]
The system should be able to match two waiting users with similar difficulty levels and put them in the same room.
Priority: High

### Todo:
- [x] Create Match Model and ORM (Week 3)
- [x] Utilise socket.io integration to make a match work between any two waiting users (Week 4)
- [x] Create Matching Page with a countdown timer (Week 4)
- [x] Match two users only if the difficulty chosen is the same (Week 5)

**Comment by boonhaii** [comment]
Requirements Completed. Closing the issue.
